/**
 * The on-device semantic tier, provisioned WITHOUT Python.
 *
 * WHY THIS REPLACES THE PYTHON BRIDGE
 * The previous adapter shelled out to `sentence-transformers`, so reaching crib's advertised
 * semantic tier meant `pip install sentence-transformers` (and, transitively, PyTorch) from a Node
 * CLI. In practice that is where installs died: a developer who installed crib from npm hit a
 * Python toolchain requirement they never signed up for, `crib doctor` reported the degraded
 * char-ngram fallback, and the semantic tier stayed git-checkout-only.
 *
 * This module provisions an ONNX runtime instead — plain npm packages, installed into the embed
 * home on demand rather than shipped in crib's tarball. Nothing about the vector space changes:
 * `multilingual-e5-large` measured G2 81.05% / G3 0.8814 through this path against the frozen
 * launch corpus, reproducing the 81.0% / 88.1% the repository already had on record for the Python
 * configuration. Same model, same weights, same numbers — one less toolchain.
 *
 * WHAT STAYS THE SAME (deliberately)
 *   • Weights land under the embed home and are pinned through the SAME integrity manifest a
 *     hand-installed model uses, so a drifted file still fails verification.
 *   • Nothing here runs at query time over the network. Provisioning fetches; serving does not.
 *   • The remote-embedder tier is untouched. "Make setup easy" must not become "quietly start
 *     sending memory text to a third party".
 *
 * THE SYNCHRONOUS-EMBEDDER PROBLEM
 * Crib's `Embedder` port is synchronous; ONNX inference is async. The Python adapter solved that by
 * spawning a process per batch — which cost a full model load (seconds) every call, and is why it
 * needed an aggressive on-disk vector cache to be usable at all. Here the model is loaded ONCE in a
 * worker thread and the main thread blocks on `Atomics.wait`, draining the reply with
 * `receiveMessageOnPort` (which does not require returning to the event loop). One load per
 * process, ~9ms per embed after it.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The npm packages the ONNX tier needs, pinned. `@huggingface/transformers` brings the ONNX runtime
 * and the tokenizers, so this is the whole surface — installed into the embed home, never added to
 * crib's own `dependencies` (the workspace runs a hard external-dependency cap, and a ~300MB native
 * runtime has no business in the tarball of a tool most users run lexically).
 */
export const ONNX_RUNTIME_PACKAGE = '@huggingface/transformers@3.7.6';

/** Layout under the embed home. Weights, runtime and adapters stay in separate subtrees so the
 *  integrity hash over an adapter never sweeps in a multi-gigabyte model file. */
export function onnxRuntimeDir(home: string): string {
  return join(home, 'runtime');
}
export function onnxModelCacheDir(home: string): string {
  return join(home, 'models');
}

/** Is the ONNX runtime already installed in this embed home? */
export function onnxRuntimeInstalled(home: string): boolean {
  return existsSync(join(onnxRuntimeDir(home), 'node_modules', '@huggingface', 'transformers'));
}

/**
 * (Re)write the generated worker. Called on EVERY setup, including when the npm install is skipped
 * because the runtime is already present.
 *
 * `onnxRuntimeInstalled` only proves `node_modules` exists, which says nothing about the version of
 * the worker sitting next to it. Writing the worker only inside the install branch meant an upgraded
 * crib kept running the PREVIOUS release's worker forever — and the failure mode is the worst kind:
 * the adapter and the worker disagree about their handshake, so the tier hangs rather than erroring.
 * The file is generated and tiny; there is no reason to preserve an old one.
 */
export function refreshOnnxWorker(home: string): void {
  const dir = onnxRuntimeDir(home);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'worker.mjs'), renderOnnxWorkerMjs());
}

/**
 * The worker that owns the model. Lives INSIDE the runtime dir so a bare
 * `import '@huggingface/transformers'` resolves against the runtime's own `node_modules` — the
 * adapter itself never imports it, which is what lets the adapter live in a different subtree.
 *
 * `allowRemoteModels: false` is the offline contract: once weights are in the cache, a serving
 * process cannot reach the network even if the cache is incomplete. It fails loudly instead.
 */
export function renderOnnxWorkerMjs(): string {
  return `/**
 * Generated by \`crib embed setup\`. Do not hand-edit.
 *
 * Loads the pinned ONNX model ONCE and answers batches over a MessagePort.
 *
 * READINESS TRAVELS OVER THE ATOMICS CHANNEL, NOT THE EVENT LOOP. The caller blocks on
 * \`Atomics.wait\`, which parks the main thread — so a \`worker.on('message')\` callback there could
 * never run, and signalling readiness that way deadlocks until the timeout. A model that fails to
 * load reports through the same channel for the same reason: an exception here would be invisible
 * to a blocked parent, and the tier would look like a hang instead of a failure.
 */
import { parentPort, workerData } from 'node:worker_threads';

const flag = new Int32Array(workerData.signal);
const port = workerData.port;
const done = () => {
  Atomics.store(flag, 0, 1);
  Atomics.notify(flag, 0);
};

let extract;
let loadError;
try {
  const { env, pipeline } = await import('@huggingface/transformers');
  env.cacheDir = workerData.cacheDir;
  // OFFLINE AT SERVE TIME. Provisioning already fetched the weights; a serving process that reached
  // out for a missing file would turn a corrupt cache into a silent network dependency.
  env.allowRemoteModels = workerData.allowRemote === true;
  env.allowLocalModels = true;
  extract = await pipeline('feature-extraction', workerData.model, { dtype: 'fp32' });
} catch (err) {
  loadError = String((err && err.message) || err);
}

port.on('message', async ({ texts }) => {
  try {
    if (loadError) throw new Error(loadError);
    // The prefix is applied HERE, in the one place both embed() and embedBatch() reach, so the two
    // can never diverge (contract 1 in the adapter).
    const out = await extract(
      texts.map((t) => workerData.prefix + t),
      { pooling: 'mean', normalize: true },
    );
    port.postMessage({ ok: true, dim: out.dims.at(-1), flat: Array.from(out.data) });
  } catch (err) {
    port.postMessage({ ok: false, error: String((err && err.message) || err) });
  }
  done();
});

port.postMessage(
  loadError ? { ok: false, error: 'model load failed: ' + loadError } : { ok: true, ready: true },
);
done();
if (parentPort) parentPort.postMessage('ready');
`;
}

/** Spec fields the generated adapter needs. Structural so this module does not depend on the
 *  setup module's richer `EmbedModelSpec` (which carries help-text and provenance fields). */
export interface OnnxAdapterSpec {
  /** The ONNX-hosted model id passed to the pipeline (e.g. `Xenova/multilingual-e5-large`). */
  onnxId: string;
  dim: number;
  prefix: string;
}

/**
 * The synchronous `Embedder` crib actually consumes.
 *
 * Two contracts this file exists to hold, both learned the hard way (see the Python adapter's
 * header): `embedBatch(texts)[i]` MUST equal `embed(texts[i])` — batching is a performance variant,
 * never a semantic one — and `id` must change whenever embedding behaviour changes, because it keys
 * the persistent vector cache.
 */
export function renderOnnxEmbedderMjs(
  spec: OnnxAdapterSpec,
  id: string,
  runtimeDir: string,
  cacheDir: string,
): string {
  return `/**
 * Generated by \`crib embed setup\` for ${spec.onnxId}. Regenerate with the same command; do not
 * hand-edit — \`crib embed install\` hashes every file here and a drifted file fails verification.
 *
 * THE TWO CONTRACTS THAT ARE EASY TO GET WRONG
 * 1. \`embedBatch(texts)[i]\` MUST equal \`embed(texts[i])\`. Both go through ONE path below, and the
 *    model prefix is applied in the worker so neither method can apply a different one.
 * 2. \`id\` must change whenever embedding behaviour changes — it keys crib's persistent vector
 *    cache, so a silent behaviour change under a stable id would serve vectors from the old space.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { MessageChannel, Worker, receiveMessageOnPort } from 'node:worker_threads';

const RUNTIME = ${JSON.stringify(runtimeDir)};
const CACHE_MODELS = ${JSON.stringify(cacheDir)};
const ID = ${JSON.stringify(id)};
const DIM = ${spec.dim};
const PREFIX = ${JSON.stringify(spec.prefix)};
const MODEL = ${JSON.stringify(spec.onnxId)};
/** Outside the adapter dir: every file under it is hashed for integrity, so a cache written here
 *  would invalidate the install on first use. */
const CACHE =
  process.env.KCRIB_EMBED_CACHE ??
  join(process.env.HOME ?? '/tmp', '.cache', 'crib-embed-vec', ID);

const memo = new Map();
const keyOf = (text) => createHash('sha256').update(text, 'utf8').digest('hex');
const pathOf = (k) => join(CACHE, k.slice(0, 2), k + '.bin');

function readCached(text) {
  const hit = memo.get(text);
  if (hit) return hit;
  const p = pathOf(keyOf(text));
  if (!existsSync(p)) return undefined;
  const buf = readFileSync(p);
  const view = new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
  const copy = new Float32Array(view); // detach from the file buffer
  memo.set(text, copy);
  return copy;
}

function writeCached(text, vec) {
  const p = pathOf(keyOf(text));
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, Buffer.from(vec.buffer, vec.byteOffset, vec.byteLength));
  memo.set(text, vec);
}

let worker;
let port;
let flag;

/** Block until the worker flips the shared flag, or the deadline passes. */
function awaitSignal(timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Atomics.load(flag, 0) === 0) {
    if (Date.now() >= deadline) return false;
    // A timeout on each wait so a lost notify cannot park the process forever.
    Atomics.wait(flag, 0, 0, 250);
  }
  return true;
}

/** Start the model worker on first use — a process that never embeds never pays the load. */
function ensureWorker() {
  if (worker) return;
  const signal = new SharedArrayBuffer(4);
  flag = new Int32Array(signal);
  Atomics.store(flag, 0, 0);
  const channel = new MessageChannel();
  port = channel.port1;
  worker = new Worker(join(RUNTIME, 'worker.mjs'), {
    workerData: {
      model: MODEL,
      prefix: PREFIX,
      cacheDir: CACHE_MODELS,
      allowRemote: false,
      signal,
      port: channel.port2,
    },
    transferList: [channel.port2],
  });
  // The worker must not hold the process open: crib exits when its work is done, not when the
  // embedder feels like it.
  worker.unref();
  // READINESS COMES OVER THE ATOMICS CHANNEL. \`Atomics.wait\` parks this thread, so a
  // \`worker.on('message')\` handler here would never run — waiting on one deadlocks until timeout.
  if (!awaitSignal(300000)) throw new Error('embedder worker did not start in 300s');
  const hello = receiveMessageOnPort(port);
  if (!hello) throw new Error('embedder worker started without reporting readiness');
  if (!hello.message.ok) throw new Error(hello.message.error);
}

function callWorker(texts) {
  ensureWorker();
  Atomics.store(flag, 0, 0);
  port.postMessage({ texts });
  // Block the main thread until the worker signals. \`receiveMessageOnPort\` drains the reply
  // without returning to the event loop, which is what makes a synchronous API possible.
  if (!awaitSignal(300000)) throw new Error('embedder worker timed out');
  const msg = receiveMessageOnPort(port);
  if (!msg) throw new Error('embedder worker returned no message');
  const r = msg.message;
  if (!r.ok) throw new Error(r.error);
  if (r.dim !== DIM) {
    throw new Error('embedder dim ' + r.dim + ' != pinned ' + DIM + ' — manifest and model disagree');
  }
  const out = [];
  for (let i = 0; i < texts.length; i += 1) {
    out.push(Float32Array.from(r.flat.slice(i * r.dim, (i + 1) * r.dim)));
  }
  return out;
}

class OnnxEmbedder {
  get id() {
    return ID;
  }

  dim() {
    return DIM;
  }

  /** The ONE code path. \`embed\` delegates here so the two can never diverge. */
  embedBatch(texts) {
    const out = new Array(texts.length);
    const missIdx = [];
    const missText = [];
    for (let i = 0; i < texts.length; i += 1) {
      const hit = readCached(texts[i]);
      if (hit) out[i] = hit;
      else {
        missIdx.push(i);
        missText.push(texts[i]);
      }
    }
    if (missText.length > 0) {
      // De-duplicate before inference: a batch repeating one string should embed it once.
      const uniq = [...new Set(missText)];
      const vecs = callWorker(uniq);
      const byText = new Map();
      uniq.forEach((t, i) => {
        writeCached(t, vecs[i]);
        byText.set(t, vecs[i]);
      });
      missIdx.forEach((idx, k) => {
        out[idx] = byText.get(missText[k]);
      });
    }
    return out;
  }

  embed(text) {
    return this.embedBatch([text])[0];
  }
}

export default new OnnxEmbedder();
`;
}

/** Result of one provisioning step, mirroring the setup module's step reporting. */
export interface OnnxStep {
  ok: boolean;
  detail: string;
}

/**
 * Install the ONNX runtime into the embed home. Isolated `npm install` in its own directory: it
 * never touches the user's project, their global node_modules, or crib's own installation.
 */
export function installOnnxRuntime(
  home: string,
  run: (cmd: string, args: string[], cwd: string) => string = (cmd, args, cwd) =>
    execFileSync(cmd, args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }),
): OnnxStep {
  const dir = onnxRuntimeDir(home);
  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, 'package.json'),
      `${JSON.stringify({ name: 'crib-embed-runtime', private: true, type: 'module' }, null, 2)}\n`,
    );
    run(
      'npm',
      ['install', '--no-audit', '--no-fund', '--loglevel', 'error', ONNX_RUNTIME_PACKAGE],
      dir,
    );
    writeFileSync(join(dir, 'worker.mjs'), renderOnnxWorkerMjs());
    if (!onnxRuntimeInstalled(home)) {
      return {
        ok: false,
        detail: `npm install completed but ${ONNX_RUNTIME_PACKAGE} is not present`,
      };
    }
    return { ok: true, detail: `installed ${ONNX_RUNTIME_PACKAGE} into ${dir}` };
  } catch (err) {
    return { ok: false, detail: `runtime install failed: ${(err as Error).message}` };
  }
}

/**
 * Fetch the model weights into the embed home's cache, so every later load is offline.
 *
 * Runs in a throwaway child process rather than in-process: the weights are large, the runtime
 * allocates aggressively while converting them, and a provisioning step must not leave that memory
 * attached to the CLI process that happens to have triggered it.
 */
export function downloadOnnxWeights(
  home: string,
  spec: OnnxAdapterSpec,
  run: (cmd: string, args: string[], cwd: string) => string = (cmd, args, cwd) =>
    execFileSync(cmd, args, {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      maxBuffer: 64 * 1024 * 1024,
    }),
): OnnxStep {
  const dir = onnxRuntimeDir(home);
  const cache = onnxModelCacheDir(home);
  mkdirSync(cache, { recursive: true });
  const script = `
import { env, pipeline } from '@huggingface/transformers';
env.cacheDir = ${JSON.stringify(cache)};
env.allowRemoteModels = true;
const extract = await pipeline('feature-extraction', ${JSON.stringify(spec.onnxId)}, { dtype: 'fp32' });
const out = await extract([${JSON.stringify(spec.prefix)} + 'dimension probe'], { pooling: 'mean', normalize: true });
console.log(JSON.stringify({ dim: out.dims.at(-1) }));
`;
  try {
    const out = run('node', ['--input-type=module', '-e', script], dir);
    const line = out.trim().split('\n').at(-1) ?? '{}';
    const dim = (JSON.parse(line) as { dim?: number }).dim;
    if (dim !== spec.dim) {
      // A dimension mismatch means the ladder's pinned dim disagrees with the real model. Failing
      // here is the point: the dim is re-checked on every load, so letting it through would turn a
      // config error into silently mis-scored retrieval.
      return { ok: false, detail: `model reports dim ${dim}, ladder pins ${spec.dim}` };
    }
    return { ok: true, detail: `weights cached under ${cache} (dim ${dim} verified)` };
  } catch (err) {
    return { ok: false, detail: `weight download failed: ${(err as Error).message}` };
  }
}

/** Write the generated adapter pair for one model into `dir`. Returns the adapter entrypoint. */
export function writeOnnxAdapter(
  home: string,
  spec: OnnxAdapterSpec,
  id: string,
  dir: string,
): string {
  mkdirSync(dir, { recursive: true });
  const entry = join(dir, 'embedder.mjs');
  writeFileSync(
    entry,
    renderOnnxEmbedderMjs(spec, id, onnxRuntimeDir(home), onnxModelCacheDir(home)),
  );
  return entry;
}
