/**
 * The MEMORY.md digest's contract.
 *
 * `renderMemoryMarkdown` is pure over a handoff response, so the interesting properties are testable
 * without a store, a clock or a repository — and they are properties about HONESTY rather than
 * layout: the file must never let an unadmitted claim look admitted, never hide that the repository
 * moved, and never present itself as something you can edit.
 */
import { describe, expect, it } from 'vitest';
import { renderMemoryMarkdown } from './memory-export.js';

/** A minimal handoff response; each test overrides only what it is about. */
function handoff(over: Record<string, unknown> = {}): never {
  return {
    openWork: [],
    pendingCaptures: [],
    needsAttention: [],
    recent: [],
    intakes: { choices: [], count: 0, resumableCount: 0 },
    continuation: { question: 'q', options: [], rationale: 'nothing is resumable' },
    degraded: [],
    counts: { openWork: 0, pendingCaptures: 0, needsAttention: 0, active: 0 },
    ...over,
  } as never;
}

const base = {
  repo: { root: '/repo', branch: 'main', head: 'abcdef1234567890' },
  generatedAt: '2026-09-21T00:00:00.000Z',
};

describe('MEMORY.md digest', () => {
  it('states that it is generated and that editing it does nothing', () => {
    const md = renderMemoryMarkdown({ ...base, handoff: handoff() });
    expect(md).toMatch(/GENERATED by/);
    expect(md).toMatch(/do not edit/);
    // The load-bearing sentence: a reader must learn WHY editing is futile, not just that it is.
    expect(md).toMatch(/every agent and IDE reads the ledger/);
    expect(md).toMatch(/crib memory observe/);
  });

  it('answers "where was I" with the progress note, not just a session id', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({
        lastSession: {
          sessionId: 'abc',
          clientId: 'claude-code',
          lastActivity: '2026-09-20T10:00:00.000Z',
          changedPaths: ['src/a.ts'],
          movedSince: false,
          summary: 'Wiring the reranker tier',
          summaryPhase: 'executing',
        },
      }),
    });
    expect(md).toContain('Wiring the reranker tier');
    expect(md).toContain('claude-code');
    expect(md).toContain('`executing`');
  });

  it('says so plainly when a session left no progress note', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({
        lastSession: {
          lastActivity: '2026-09-20T10:00:00.000Z',
          changedPaths: [],
          movedSince: false,
        },
      }),
    });
    // An absent note is a real state; rendering a blank would read like a bug.
    expect(md).toMatch(/No progress note was saved/);
  });

  it('warns when the repository moved since that session', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({
        lastSession: {
          lastActivity: '2026-09-20T10:00:00.000Z',
          changedPaths: [],
          movedSince: true,
          summary: 'Something',
        },
      }),
    });
    expect(md).toMatch(/repository has moved/);
  });

  it('COUNTS withheld candidates without quoting them', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({
        counts: { openWork: 0, pendingCaptures: 2, needsAttention: 0, active: 0 },
        pendingCaptures: [
          { id: 'cap:1', subject: 's', observation: 'SECRET_UNADMITTED_TEXT' },
          { id: 'cap:2', subject: 's', observation: 'another' },
        ],
      }),
    });
    expect(md).toMatch(/2 captured learnings are staged/);
    // The whole point: unverified text must not sit beside verified text looking identical.
    expect(md).not.toContain('SECRET_UNADMITTED_TEXT');
    expect(md).toMatch(/--include-pending/);
  });

  it('--include-pending quotes them, under a heading that says they are untrusted', () => {
    const md = renderMemoryMarkdown({
      ...base,
      includePending: true,
      handoff: handoff({
        counts: { openWork: 0, pendingCaptures: 1, needsAttention: 0, active: 0 },
        pendingCaptures: [{ id: 'cap:1', subject: 's', observation: 'SECRET_UNADMITTED_TEXT' }],
      }),
    });
    expect(md).toContain('SECRET_UNADMITTED_TEXT');
    expect(md).toMatch(/not admitted/);
    expect(md).toMatch(/untrusted leads/);
  });

  it('names the verdicts on claims that stopped holding', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({
        needsAttention: [
          {
            id: 'mem:1',
            subject: 'sym:a#b@L1',
            claim: 'a claim that drifted',
            evidence: 'degraded',
            applicability: 'orphaned',
          },
        ],
      }),
    });
    expect(md).toMatch(/Needs review/);
    expect(md).toMatch(/evidence \*\*degraded\*\*/);
    expect(md).toMatch(/applicability \*\*orphaned\*\*/);
  });

  it('reports a degraded read instead of rendering a confident empty page', () => {
    const md = renderMemoryMarkdown({
      ...base,
      handoff: handoff({ degraded: ['journal unreadable'] }),
    });
    expect(md).toMatch(/Degraded reads/);
    expect(md).toMatch(/does not mean the information does not exist/);
  });

  it('omits empty sections rather than printing hollow headings', () => {
    const md = renderMemoryMarkdown({ ...base, handoff: handoff() });
    expect(md).not.toMatch(/## Needs review/);
    expect(md).not.toMatch(/## Withheld/);
    expect(md).not.toMatch(/## Where I left off/);
  });
});
