/**
 * `crib memory export` — a human-readable MEMORY.md, GENERATED FROM the ledger.
 *
 * WHY THIS IS ONE-WAY, and why that is the whole design. The obvious request is a `memory.md` you can
 * open and also edit, the way several tools do it. Making it writable would make it a second source
 * of truth, which this project's own protocol forbids ("no substitute and no side-store"), and the
 * divergence would be silent: edit the file, and the ledger — which is what every agent and every IDE
 * actually reads — still says the old thing. So this renders and never ingests. The file is a VIEW.
 *
 * It also cannot be a faithful serialization, and pretending otherwise would be worse than not
 * shipping it. The ledger is append-only and bi-temporal: a record is superseded rather than edited,
 * each carries evidence verdicts and a four-axis freshness state, and recall re-derives all of that
 * against today's code. Markdown has nowhere to put any of it. What this file gives you is the part
 * that IS flat — what was I doing, what is unfinished, what has been learned and still holds — with
 * the verdicts named in prose so a reader can see which claims are load-bearing.
 *
 * Untrusted candidates are COUNTED, not quoted, exactly as the default `crib memory recall` view does
 * (F10). A digest that printed staged claims alongside admitted ones would hand a reader a file where
 * verified and unverified text look identical, which is the one thing the admission gate exists to
 * prevent. `--include-pending` opts into their text, under its own clearly-labelled heading.
 */
import type { HandoffResponse } from '@knowledge-crib/memory';

export interface MemoryExportInput {
  handoff: HandoffResponse;
  /** Repository the digest describes, for the header. */
  repo: { root: string; branch?: string; head?: string };
  /** ISO timestamp the digest was rendered at. */
  generatedAt: string;
  /** Quote staged candidates rather than only counting them. */
  includePending?: boolean;
  /** The command that regenerates this file, printed in the header. */
  command?: string;
}

/** Trim a claim to one readable line without cutting mid-word where avoidable. */
function oneLine(text: string, max = 240): string {
  const flat = String(text ?? '')
    .replace(/\s+/g, ' ')
    .trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut}…`;
}

function section(title: string, body: string[]): string[] {
  if (body.length === 0) return [];
  return [`## ${title}`, '', ...body, ''];
}

/**
 * Render the digest. PURE over its input so the shape is testable without a store, a clock or a
 * repository — the same discipline `handoff` itself follows.
 */
export function renderMemoryMarkdown(input: MemoryExportInput): string {
  const { handoff, repo, generatedAt } = input;
  const cmd = input.command ?? 'crib memory export';
  const lines: string[] = [
    `<!-- GENERATED by \`${cmd}\` — do not edit.`,
    '',
    '     This file is a VIEW of the memory ledger, not the ledger itself. Editing it changes',
    '     nothing: every agent and IDE reads the ledger (`crib memory recall`, the `memory` MCP',
    '     tool), and your edit would silently disagree with it. To record something durable, use',
    '     `crib memory observe` (an agent, with evidence) or `crib memory remember` (a human, from a',
    '     terminal) — both go through the admission gate this file only reports on.',
    '',
    '     It is also lossy by nature. The ledger is append-only and bi-temporal — records are',
    '     superseded rather than edited, and each carries evidence and freshness verdicts re-derived',
    '     against today’s code. Markdown cannot hold that, so the verdicts are named in prose here',
    '     and the authoritative answer is always a recall. -->',
    '',
    '# Memory digest',
    '',
    `**Repository:** \`${repo.root}\`${repo.branch ? ` · branch \`${repo.branch}\`` : ''}${
      repo.head ? ` · \`${repo.head.slice(0, 12)}\`` : ''
    }`,
    `**Generated:** ${generatedAt}`,
    '',
  ];

  // ── where was I ────────────────────────────────────────────────────────────
  const ls = handoff.lastSession;
  if (ls) {
    const body = [
      ls.summary
        ? `**${oneLine(ls.summary)}**`
        : '**No progress note was saved for this session — only its coordinates were recorded.**',
      '',
      `- ${ls.clientId ?? 'an agent'}${ls.branch ? ` on \`${ls.branch}\`` : ''} · ${ls.lastActivity}${
        ls.summaryPhase ? ` · phase \`${ls.summaryPhase}\`` : ''
      }`,
    ];
    if (ls.movedSince) {
      body.push(
        '- ⚠️ The repository has moved to a different branch or commit since then — re-check any plan against the tree as it is now.',
      );
    }
    if (ls.changedPaths.length > 0) {
      const shown = ls.changedPaths.slice(0, 10);
      body.push(
        `- Uncommitted then: ${shown.map((p) => `\`${p}\``).join(', ')}${
          ls.changedPathsTruncated || ls.changedPaths.length > shown.length ? ' …' : ''
        }`,
      );
    }
    lines.push(...section('Where I left off', body));
  }

  // ── unfinished work ────────────────────────────────────────────────────────
  // `intakes.choices` are ResumeBrief rows (the work itself). `continuation.options` is the
  // question-shaped view of the same set — used below for the recommendation, not duplicated here.
  const workBody: string[] = [];
  for (const brief of handoff.intakes.choices) {
    workBody.push(
      `- **${oneLine(brief.interpretation?.outcome ?? brief.original, 200)}**  _(${brief.phase}${
        brief.idleDays !== undefined ? `, idle ${brief.idleDays}d` : ''
      })_`,
    );
    if (brief.nextSafeAction) workBody.push(`  - Next: ${oneLine(brief.nextSafeAction, 300)}`);
    // Drift and blockers are the two reasons a resume is unsafe, so they are never folded away.
    if (brief.repositoryDrift) {
      workBody.push(
        '  - ⚠️ The repository moved since this was checkpointed — re-check the plan against the tree as it is now.',
      );
    }
    for (const blocker of brief.blockers ?? [])
      workBody.push(`  - ⚠️ Blocked: ${oneLine(blocker, 200)}`);
    for (const conflict of brief.conflicts ?? []) {
      workBody.push(`  - ⚠️ Conflicting ${conflict.field}: ${conflict.values.join(' | ')}`);
    }
  }
  if (workBody.length > 0 && handoff.continuation?.rationale) {
    workBody.push('', `_${oneLine(handoff.continuation.rationale, 240)}_`);
  }
  for (const w of handoff.openWork) {
    workBody.push(
      `- ${w.subject ? `\`${w.subject}\` — ` : ''}${oneLine(w.observation ?? w.action ?? w.lastPhase, 200)} _(${w.lastActivity})_`,
    );
  }
  lines.push(...section('Unfinished work', workBody));

  // ── what has been learned ──────────────────────────────────────────────────
  const recentBody = handoff.recent.map(
    (r) => `- **${r.kind}** · \`${r.subject}\`\n  - ${oneLine(r.claim)}`,
  );
  lines.push(
    ...section(
      `What is known (${handoff.counts.active} admitted claim${handoff.counts.active === 1 ? '' : 's'})`,
      recentBody,
    ),
  );

  // ── what stopped being true ────────────────────────────────────────────────
  const attentionBody = handoff.needsAttention.map(
    (a) =>
      `- \`${a.subject}\` — evidence **${a.evidence}**, applicability **${a.applicability}**\n  - ${oneLine(a.claim)}`,
  );
  if (attentionBody.length > 0) {
    attentionBody.unshift(
      'These held once and no longer do — the code moved underneath them. Supersede or re-ground each before relying on it.',
      '',
    );
  }
  lines.push(...section('Needs review', attentionBody));

  // ── the trust gate, reported rather than hidden ────────────────────────────
  const pendingCount = handoff.counts.pendingCaptures;
  if (pendingCount > 0) {
    const body = input.includePending
      ? [
          'Staged but **not admitted** — untrusted leads, never established facts. Quoted here because',
          '`--include-pending` was passed.',
          '',
          ...handoff.pendingCaptures.map(
            (p) => `- \`${p.subject}\`\n  - ${oneLine(p.observation)}`,
          ),
        ]
      : [
          `${pendingCount} captured learning${pendingCount === 1 ? '' : 's'} ${
            pendingCount === 1 ? 'is' : 'are'
          } staged and **not admitted**, so ${pendingCount === 1 ? 'it is' : 'they are'} not shown here.`,
          '',
          'This is the trust gate working, not an omission: an unverified claim printed beside verified',
          'ones would be indistinguishable from them. Re-run with `--include-pending` to read them as',
          'untrusted, or admit them with `crib memory activate`.',
        ];
    lines.push(...section('Withheld', body));
  }

  if (handoff.degraded.length > 0) {
    lines.push(
      ...section('Degraded reads', [
        'Part of the ledger could not be read, so this digest is incomplete — an absent section below',
        'does not mean the information does not exist.',
        '',
        ...handoff.degraded.map((d) => `- ${d}`),
      ]),
    );
  }

  lines.push('---', '', `Regenerate with \`${cmd}\`. The ledger is the source of truth.`, '');
  return lines.join('\n');
}
