/**
 * docs-stats — the M4.4 canonical stats source generator.
 *
 * The drift problem this solves: `docs/README.md` (and several point-in-time assessment docs)
 * hardcoded "392 tests green, 7-language deep extraction". Both numbers went stale — the suite is
 * now ~10× larger and PHP was added as an 8th code language (9 with Markdown). A hardcoded stat in
 * prose drifts silently; a GENERATED stat regenerates from the real codebase every run.
 *
 * This script scans the real tree (no test execution — fast + deterministic) and writes
 * `docs/STATS.md`, the single canonical source docs should reference instead of restating numbers.
 * The drift gate (`docs-site-check.mjs`) regenerates to a temp file and asserts byte-identical, so a
 * committed STATS.md that lags the tree fails the gate.
 *
 * What it counts (all static, deterministic):
 *   - packages: every `packages/*` dir with a package.json `name`
 *   - parser languages: extractor subdirs of `packages/parsers/src/` (excludes registry/types/pool/fuzz)
 *   - eval fixture languages: the FIXTURE_LANGS list from scripts/eval/harness.mjs
 *   - test files: every `.test.ts` file under `packages/`
 *   - test call-sites: regex count of `it(`/`test(` in test files (call-sites, not runtime count —
 *     `it.each` is one call-site; the runtime total is in CI / `pnpm test`)
 *   - graph stats remain authoritative in `.crib/graph/manifest.json` but are intentionally omitted
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..');
const OUT = join(REPO, 'docs', 'STATS.md');

const walk = (dir, acc = []) => {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist' || entry.startsWith('.')) continue;
      walk(p, acc);
    } else if (p.endsWith('.test.ts')) {
      acc.push(p);
    }
  }
  return acc;
};

const testFiles = walk(join(REPO, 'packages')).sort();
let testCallSites = 0;
for (const f of testFiles) {
  const src = readFileSync(f, 'utf8');
  // `it(` or `test(` as a call — count call-sites, not runs. Strip block/line comments first so a
  // commented-out test isn't counted. (Good enough for a drift sentinel; not a runtime count.)
  const stripped = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
  testCallSites += (stripped.match(/\b(?:it|test)\s*\(/g) ?? []).length;
}

// packages: dirs under packages/ with a package.json name.
const pkgDir = join(REPO, 'packages');
const packages = readdirSync(pkgDir)
  .filter((d) => statSync(join(pkgDir, d)).isDirectory())
  .map((d) => {
    const pj = join(pkgDir, d, 'package.json');
    try {
      return { dir: d, name: JSON.parse(readFileSync(pj, 'utf8')).name ?? d };
    } catch {
      return null;
    }
  })
  .filter(Boolean);

// parser languages: extractor subdirs of parsers/src (exclude non-extractor files + the fuzz dir).
const parserSrc = join(REPO, 'packages', 'parsers', 'src');
const nonLang = new Set(['registry.ts', 'types.ts', 'tree-sitter-pool.ts', 'index.ts']);
const parserLangs = readdirSync(parserSrc)
  .filter((d) => {
    const p = join(parserSrc, d);
    return statSync(p).isDirectory() && d !== 'fuzz';
  })
  .concat(
    readdirSync(parserSrc)
      .filter(
        (f) =>
          f.endsWith('.ts') && !f.endsWith('.test.ts') && !nonLang.has(f) && !f.includes('.test.'),
      )
      .map((f) => f.replace(/\.ts$/, '')),
  )
  .map((d) => d.replace(/\.ts$/, ''))
  .sort();

// eval fixture languages: parse the FIXTURE_LANGS array from harness.mjs.
let evalLangs = [];
try {
  const harness = readFileSync(join(REPO, 'scripts', 'eval', 'harness.mjs'), 'utf8');
  const m = harness.match(/FIXTURE_LANGS\s*=\s*\[([^\]]*)\]/s);
  if (m) {
    evalLangs = [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]).sort();
  }
} catch {
  /* harness absent — leave empty */
}

// NOTE: soul node/edge counts are deliberately NOT included — they change on every `crib update`
// (the M4.3 action refreshes the committed soul on every merge), so they would make this file
// drift on every merge and turn the docs-site:check gate into noise. The canonical stats here are
// the stable structural numbers (packages, languages, test surface) that only move on real changes.

const lines = [];
lines.push(
  '<!-- Generated by scripts/docs-stats.mjs — DO NOT edit by hand. Re-run `pnpm docs:stats` to refresh. -->',
);
lines.push('');
lines.push('# Knowledge-crib — canonical stats');
lines.push('');
lines.push('Single source of truth for the numbers that drift when stated in prose. Regenerated');
lines.push(
  'from the real tree by `scripts/docs-stats.mjs`; the `docs-site:check` gate asserts this',
);
lines.push('file is fresh. Reference this file instead of restating a count in narrative docs.');
lines.push('');
lines.push('| metric | value |');
lines.push('| --- | --- |');
lines.push(`| packages | ${packages.length} (${packages.map((p) => p.name).join(', ')}) |`);
lines.push(`| parser languages | ${parserLangs.length} (${parserLangs.join(', ')}) |`);
lines.push(`| eval fixture languages | ${evalLangs.length} (${evalLangs.join(', ')}) |`);
lines.push(`| test files | ${testFiles.length} |`);
lines.push(`| test call-sites (static) | ${testCallSites} |`);
lines.push('');
lines.push(
  '> Test call-sites are a static count of `it(`/`test(` occurrences (excluding comments),',
);
lines.push(
  '> not the runtime total — `it.each` is one call-site. The runtime total is in CI / `pnpm test`.',
);
lines.push('');
writeFileSync(OUT, lines.join('\n'));
process.stdout.write(
  `docs:stats — wrote ${OUT} (${packages.length} packages, ${parserLangs.length} parser langs, ${testFiles.length} test files)\n`,
);
